name: "Build"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.db'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Grant gradle permission
      - run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: test

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest
